# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('audio', models.FileField(upload_to='audios/%Y/%m/%d')),
                ('is_private', models.BooleanField(default=False, help_text='Weather the audio file is private or public.')),
                ('audio_type', models.CharField(choices=[('P', 'Primary'), ('G', 'Generic')], default='G', max_length=1)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image_w', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('image_h', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, default=None, height_field='image_h', upload_to='images/%Y/%m/%d', width_field='image_w')),
                ('is_private', models.BooleanField(default=False, help_text='Weather the image is private or public.')),
                ('image_type', models.CharField(choices=[('P', 'Primary'), ('G', 'Generic')], default='G', max_length=1)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d')),
                ('is_private', models.BooleanField(default=False, help_text='Weather the video file is private or public.')),
                ('video_type', models.CharField(choices=[('P', 'Primary'), ('G', 'Generic')], default='G', max_length=1)),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/%Y/%m/%d')),
                ('object_id', models.PositiveIntegerField()),
                ('link', models.URLField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
