# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_hstore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of bank.', max_length=255, null=True)),
                ('branch', models.CharField(blank=True, help_text='Branch of bank company is associated.', max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, help_text='Pan card number of company.', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserIncentives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('application', models.CharField(default='25%', help_text='Incentives for application on job post.', max_length=255)),
                ('job_post', models.CharField(default='500', help_text='Incentives for job post.', max_length=255)),
                ('user_paid', models.CharField(default='500', help_text='Incentives for user payment.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', related_query_name='preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('app_notification', models.BooleanField(default=True)),
                ('push_notification', models.BooleanField(default=True)),
                ('sms_notification', models.BooleanField(default=True)),
                ('email_notification', models.BooleanField(default=True)),
                ('profile_state', models.CharField(choices=[('PB', 'public'), ('PR', 'private'), ('DA', 'disabled')], default='PB', help_text='Profile states of user.', max_length=2)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userinvites',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userinvites',
            name='user',
        ),
        migrations.AlterField(
            model_name='bio',
            name='data',
            field=django_hstore.fields.DictionaryField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, db_index=True, help_text='Educational degree for e.g BTech, M.sc, B.Com etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, db_index=True, help_text='In which stream of course degree was achieved.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Feature Film'), (2, 'Tv show'), (3, 'Advertisement'), (4, 'Theatre'), (5, 'Modelling'), (5, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('NS', 'Not_specified')], db_index=True, default='NS', max_length=2),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Should be valid email, e.g. name@example.com', max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text="User's phone number.", max_length=10, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='UserInvites',
        ),
        migrations.AddField(
            model_name='company',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Bank details for the company.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Bank'),
        ),
        migrations.AddField(
            model_name='person',
            name='incentive_plan',
            field=models.ForeignKey(blank=True, help_text='Incentive plan details.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserIncentives'),
        ),
    ]
