# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160725_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email of user is verified?'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text='Phone number of user is verified?'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_passcode',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Passcode for user's phone verification"),
        ),
    ]
