# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_profile_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_completion_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text="How much percentage user's profile is filled."),
        ),
    ]
