# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_profile_completion_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stageroute_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='StageRoute ranking for the user.', max_digits=2, null=True),
        ),
    ]
