# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 07:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_stageroute_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stageroute_score',
            field=models.DecimalField(decimal_places=1, default=0, help_text='StageRoute ranking for the user.', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
