# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 10:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160912_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stageroute_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='StageRoute ranking for the user.', validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
