# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 09:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20160913_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested_professions',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('feature_film', 'feature_film'), ('internet_movie', 'internet_movie'), ('theatre', 'theatre'), ('television', 'television'), ('modelling', 'modelling'), ('advertising', 'advertising'), ('other', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_completion_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text="How much percentage user's profile is filled.", validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
