# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 13:53
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160915_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interested_professions',
            field=select_multiple_field.models.SelectMultipleField(choices=[('feature_film', 'feature_film'), ('internet_movie', 'internet_movie'), ('theatre', 'theatre'), ('television', 'television'), ('modelling', 'modelling'), ('advertising', 'advertising'), ('other', 'other')], default='other', max_length=50),
        ),
    ]
