# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 08:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='job',
            name='min_age',
        ),
        migrations.AddField(
            model_name='job',
            name='ages',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, help_text='Age range required for this role.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='audition_range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, help_text='Audition range', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='auditions_per_day',
            field=models.IntegerField(blank=True, help_text='Number of auditions to do per day for this job.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='body_type',
            field=models.CharField(blank=True, choices=[('skinny', 'skinny'), ('bulky', 'bulky'), ('slim', 'slim'), ('athletic', 'athletic'), ('muscular', 'muscular'), ('curvy', 'curvy'), ('busty', 'busty'), ('bulky', 'bulky'), ('', 'does_not_matter')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='budgets',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, help_text='budget range amount to be spent on the job.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('red', 'red'), ('blue', 'blue'), ('grey', 'grey'), ('black', 'black'), ('brown', 'brown'), ('other', 'other'), ('', 'does_not_matter')], default='', help_text='Peferred eye color.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='featured',
            field=models.BooleanField(default=False, help_text='Is job featured.'),
        ),
        migrations.AddField(
            model_name='job',
            name='hair_type',
            field=models.CharField(blank=True, choices=[('straight', 'straight'), ('wavy', 'wavy'), ('curly', 'curly'), ('scanty', 'scanty'), ('bald', 'bald'), ('half_bald', 'half_bald'), ('', 'does_not_matter')], default='', help_text='Preferred hair type.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='heights',
            field=django.contrib.postgres.fields.ranges.FloatRangeField(blank=True, help_text='Range of height required.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'english'), ('hindi', 'hindi'), ('gujarati', 'gujarati'), ('bengali', 'bengali'), ('', 'does_not_matter')], default='', help_text='Preferred languages.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='number_of_vacancies',
            field=models.IntegerField(default=1, help_text='How many positions are open for this job.'),
        ),
        migrations.AddField(
            model_name='job',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('fair', 'fair'), ('dark', 'dark'), ('wheatish', 'wheatish'), ('', 'does_not_matter')], default='', help_text='Preferred skin type.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('feature_film', 'feature_film'), ('internet_movie', 'internet_movie'), ('theatre', 'theatre'), ('television', 'television'), ('modelling', 'modelling'), ('advertising', 'advertising'), ('other', 'other')], help_text='Type of job.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('NS', 'Not_specified')], default='NS', max_length=2),
        ),
    ]
