# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20160725_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PA', 'Unapproved'), ('A', 'Approved'), ('R', 'Removed'), ('C', 'Closed')], default='PA', max_length=2),
        ),
    ]
