# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20160908_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.CharField(blank=True, help_text='Useful for job posters. A quick note they can refere later.', max_length=255, null=True),
        ),
    ]
