# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('intiated', 'Initiated'), ('pipelined', 'Pipelined'), ('ignored', 'Ignored'), ('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('invited', 'Invited'), ('invite_accepted', 'Invite_accepted'), ('invite_rejected', 'Invite_rejected'), ('audition_done', 'Audition_done'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('on_hold', 'On_hold'), ('job_closed', 'Job_closed')], default='intiated', max_length=50, protected=True, verbose_name='Application state.')),
            ],
            options={
                'verbose_name_plural': 'Applications',
                'verbose_name': 'Application',
            },
            bases=(models.Model, django_fsm.ConcurrentTransitionMixin),
        ),
        migrations.CreateModel(
            name='AuditionInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date', models.DateTimeField(blank=True, help_text='Date of Audition/Interview.', null=True)),
                ('applications', models.ManyToManyField(related_name='audition_invites', related_query_name='audition_invite', to='application.Application')),
                ('location', models.ForeignKey(blank=True, help_text='Location for audition.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='cities.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobileAppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('version_code', models.IntegerField(unique=True)),
                ('is_required', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
