# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20160628_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditioninvite',
            name='audition_type',
            field=models.CharField(blank=True, choices=[('television', 'television'), ('print', 'print'), ('movie', 'movie'), ('theatre', 'theatre'), ('digital', 'digital')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auditioninvite',
            name='message_id',
            field=models.IntegerField(blank=True, help_text='Message id for message sent along with invite.', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=django_fsm.FSMField(choices=[('intiated', 'Initiated'), ('pipelined', 'Pipelined'), ('ignored', 'Ignored'), ('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('invited', 'Invited'), ('invite_accepted', 'Invite_accepted'), ('invite_rejected', 'Invite_rejected'), ('audition_done', 'Audition_done'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('on_hold', 'On_hold'), ('job_closed', 'Job_closed')], db_index=True, default='intiated', max_length=50, protected=True, verbose_name='Application state.'),
        ),
        migrations.AlterField(
            model_name='auditioninvite',
            name='location',
            field=models.TextField(blank=True, help_text='Address location for audition.', null=True),
        ),
    ]
