# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20160725_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappversion',
            name='app_type',
            field=models.CharField(choices=[('talent', 'talent'), ('director', 'director'), ('agent', 'agent')], default='talent', max_length=255),
        ),
    ]
