# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_mobileappversion_app_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileappversion',
            name='version_code',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='mobileappversion',
            unique_together=set([('version_code', 'app_type')]),
        ),
    ]
