# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20160811_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('can_reject_candidate', 'Can reject a candiate.'),), 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
    ]
