# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20160901_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reason_for_rejection',
            field=models.CharField(blank=True, help_text='Reason why the application was rejected.', max_length=255, null=True),
        ),
    ]
